export const workdData = [
  {
    id: 1,
    title: 'developer',
    job: 'Flagrant',
    year: 'DEC 2023 - JUNE 2024',
    text: "During my tenure, I worked on a variety of client projects both external and internal, where I developed and maintained features to enhance user experiences. My responsibilities included completing user stories, search engine optimization, resolving bugs, and continuously improving usability. One notable achievement was contributing to a project recognized with four CSS Design awards for www.PeoplesTech.com. These accolades included Best UI Design, Best UX Design, Best Innovation, and Special Kudos from CSSDA judges, showcasing our team's commitment to excellence in web design and user interface development.",
    techStack: [
      'Ruby on Rails',
      'Bridgetown',
      'Decap CMS',
      'CMS',
      'SEO',
      'Netlify',
      'Tailwind',
      'Javascript',
      'HTML5',
      'CSS',
      'Git',
    ],
  },
  {
    id: 2,
    title: 'SOFTWARE ENGINEER',
    job: 'Acquia Inc',
    year: 'APR 2023 - DEC 2023',
    text: 'Led the implementation of user-accessible components and features, ensuring seamless integration and functionality. Developed and maintained client-specific features, emphasizing reliability and user satisfaction. Created comprehensive unit tests to validate the robustness of features and components. Successfully delivered on user stories, resolved bugs, and enhanced overall user experience.',
    techStack: [
      'ReactJS',
      'JavaScript',
      'HTML5',
      'CSS',
      'SASS',
      'Git',
      'GitHub',
      'Jest.js',
    ],
  },
  {
    id: 3,
    title: 'APPLICATION DEVELOPER',
    job: 'American Family Insurance',
    year: '2017 - 2021',
    text: 'I contributed to the development and maintenance of features on Amfam.com, including the creation of one-page Quoting tools. I utilized front-end frameworks like AngularJS and ReactJS with Redux, ensuring robust functionality and seamless user experiences. I authored unit tests to validate the performance of features and components. Throughout the development process, I completed user stories and resolved bugs on existing web pages, significantly enhancing speed and functionality. Collaborating closely with team members, I participated in two-week sprints to implement new features. At the end of each sprint, I conducted demonstrations of completed features to the team.',
    techStack: [
      'ReactJS',
      'Redux',
      'AngularJS',
      'CI/CD',
      'Adobe XD',
      'AWS',
      'PostgreSQL',
      'Material UI',
      'JavaScript',
      'HTML5',
      'CSS',
      'SASS',
      'Git',
      'GitHub',
      'Jest.js',
    ],
  },
  {
    id: 4,
    title: 'FRONT-END DEVELOPER | GRAPHIC DESIGNER',
    job: 'Adorable IO',
    year: '2015 - 2017',
    text: 'I specialized in designing and developing UX/UI for websites, including wire-framing and creating logos, posters, icons, and other visual assets. I collaborated closely with peers on website design and development projects. Additionally, I volunteered at the YWeb Career Academy, gaining valuable experience in the field. I utilized GitHub for version control and successfully deployed websites using Heroku.',
    techStack: [
      'UX/UI',
      'JavaScript',
      'HTML5',
      'CSS',
      'Git',
      'GitHub',
      'Heroku',
      'Adobe Illustrator',
    ],
  },
];
